---
title: "Subgroups \n Chapter 8"
author: "Nick Lauerman"
date: ""
output: 
  pdf_document: 
    fig_caption: yes
    fig_height: 6.5
    fig_width: 6.5
    toc: yes
    toc_depth: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_chunk$set(cache = TRUE)
#knitr::opts_chunk$set(cache.path = "./Cache/")
```

# Libraries and data used
## Libraries
```{r}
library(UserNetR)
library(igraph)
library(intergraph)
```

## Data
```{r}
data("DHHS")
data("Moreno")
data("Facebook")
```

# Social Cohesion
## Cliques
```{r}
clqexmp <- graph.formula(A:B:C:D--A:B:C:D,D-E,E-F-G-E)
plot(clqexmp, 
     layout = layout_with_fr)

clique.number(clqexmp)
cliques(clqexmp,
        min = 3)
maximal.cliques(clqexmp,
                min = 3)
largest.cliques(clqexmp)
V(clqexmp)[unlist(largest.cliques(clqexmp))]

g25 <- erdos.renyi.game(25,
                        75, 
                        type = "gnm")
g50 <- erdos.renyi.game(50,
                        150, 
                        type = "gnm")
g100 <- erdos.renyi.game(100,
                         300, 
                         type = "gnm")
g500 <- erdos.renyi.game(500,
                         1500, 
                         type = "gnm")
g1000 <- erdos.renyi.game(1000,
                          3000, 
                          type = "gnm")
g5000 <- erdos.renyi.game(5000,
                          15000, 
                          type = "gnm")
g10000 <- erdos.renyi.game(10000,
                           30000, 
                           type = "gnm")
nodes <- c(25,
           50,
           100,
           500,
           1000,
           5000,
           10000)
lrgclg <- c(clique.number(g25),
            clique.number(g50),
            clique.number(g100),
            clique.number(g500),
            clique.number(g1000),
            clique.number(g5000),
            clique.number(g10000))
numclq <- c(length(cliques(g25,
                           min = 3)),
            length(cliques(g50,
                           min = 3)),
            length(cliques(g100,
                           min = 3)),
            length(cliques(g500,
                           min = 3)),
            length(cliques(g1000,
                           min = 3)),
            length(cliques(g5000,
                           min = 3)),
            length(cliques(g10000,
                           min = 3)))
clqinfo <- data.frame(
  Nodes = nodes,
  Largest = lrgclg,
  number = numclq)
clqinfo
```

## k-Cores
```{r}
data(DHHS)
iDHHS <- asIgraph(DHHS)
graph.density(iDHHS)
iDHHS <- subgraph.edges(iDHHS,
                        E(iDHHS)[collab > 2])
graph.density(iDHHS)
coreness <- graph.coreness(iDHHS)
table(coreness)
maxCoreness <- max(coreness)
maxCoreness
Vname <- get.vertex.attribute(iDHHS,
                              name = "vertex.names",
                              index = V(iDHHS))
V(iDHHS)$name <- Vname
V(iDHHS)$color <- coreness + 1
op <- par(mar = rep(0,4))
plot(iDHHS,
     vertex.label.cex = 0.8)
par(op)
colors <- rainbow(maxCoreness)
op <- par(mar = rep(0,4))
plot(iDHHS,
     vertex.label = coreness,
     vertex.color = colors[coreness])
par(op)

V(iDHHS)$name <- coreness
V(iDHHS)$color <- colors[coreness]
iDHHS1_6 <- iDHHS
iDHHS2_6 <- induced.subgraph(iDHHS,
                             vids = which(coreness > 1))
iDHHS3_6 <- induced.subgraph(iDHHS,
                             vids = which(coreness > 2))
iDHHS4_6 <- induced.subgraph(iDHHS,
                             vids = which(coreness > 3))
iDHHS5_6 <- induced.subgraph(iDHHS,
                             vids = which(coreness > 4))
iDHHS6_6 <- induced.subgraph(iDHHS,
                             vids = which(coreness > 5))
lay <- layout.fruchterman.reingold(iDHHS)
op <- par(mfrow = c(3,2),
          mar = c(3, 0, 2, 0))
plot(iDHHS1_6,
     layout = lay,
     main = "All k-cores")
plot(iDHHS2_6,
     layout = lay[which(coreness > 1), ],
     main = "k-cores 2-6")
plot(iDHHS3_6,
     layout = lay[which(coreness > 2), ],
     main = "k-cores 3-6")
plot(iDHHS4_6,
     layout = lay[which(coreness > 3), ],
     main = "k-cores 4-6")
plot(iDHHS5_6,
     layout = lay[which(coreness > 4), ],
     main = "k-cores 5-6")
plot(iDHHS6_6,
     layout = lay[which(coreness > 5), ],
     main = "k-cores 6-6")
par(op)
```

# Community Detectiom
## Modularity
```{r}
g1 <- graph.formula(A-B-C-A,
                    D-E-F-D,
                    G-H-I-G,
                    A-D-G-A)
V(g1)$grp_good <- c(1,1,1,2,2,2,3,3,3)
V(g1)$grp_bad <-  c(1,2,3,2,3,1,3,1,2)
op <- par(mfrow = c(1,2))
plot(g1,
     vertex.color = (V(g1)$grp_good),
     vertex.size = 20,
     main = "Good Grouping")
plot(g1,
     vertex.color = (V(g1)$grp_bad),
     vertex.size = 20,
     main = "Bad Grouping")
par(op)
modularity(g1,
           V(g1)$grp_good)
modularity(g1,
           V(g1)$grp_bad)
data(DHHS)
iDHHS <- asIgraph(DHHS)
table(V(iDHHS)$agency)
V(iDHHS)[1:10]$agency
modularity(iDHHS,
           (V(iDHHS)$agency + 1))
data("Moreno")
iMoreno <- asIgraph(Moreno)
table(V(iMoreno)$gender)
modularity(iMoreno,
           V(iMoreno)$gender)
data("Facebook")
levels(factor(V(Facebook)$group))
grp_mun <- as.numeric(factor(V(Facebook)$group))
modularity(Facebook, grp_mun)
```


