---
title: "Advanced Network Graphics part B"
author: "Nick Lauerman"
date: ""
output: 
  pdf_document: 
    fig_caption: yes
    fig_height: 6.5
    fig_width: 6.5
    toc: yes
    toc_depth: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_chunk$set(cache = TRUE)
#knitr::opts_chunk$set(cache.path = "./Cache/")
```

# Libraries and data used
## Libraries
```{r}
library(UserNetR)
library(statnet)
library(circlize)
library(sna)
library(ggplot2)
library(Hmisc)
```

## Data
```{r}
data(FIFA_Nether)
```

# Specialized Network Diagrams (continued)
continuation with next subsectiom from part A.

## Chord Diagrams
```{r}
FIFAm <- as.sociomatrix(FIFA_Nether,
                        attrname = "passes")
names <- c("GK1",
           "DF3",
           "DF4",
           "DF5",
           "MF6",
           "FW7",
           "FW9",
           "MK10",
           "FW11",
           "DF2",
           "MF8")
rownames(FIFAm) <- names
colnames(FIFAm) <- names
FIFAm

FIFAm[FIFAm < 10] <- 0
FIFAm

chordDiagram(FIFAm)

grid.col <- c("#AA3939",
              rep("#AA6C39",
                4),
              rep("#2D882D",
                  3),
              rep("#226666",
                  3))
chordDiagram(FIFAm,
             directional = TRUE,
             grid.col = grid.col,
             order = c("GK1",
                       "DF2",
                       "DF3",
                       "DF4",
                       "DF5",
                       "MF6",
                       "FW7",
                       "FW9",
                       "MF8",
                       "MK10",
                       "FW11"))
```

## Heatmaps for Network data
```{r}
data("FIFA_Nether")
FIFAm <- as.sociomatrix(FIFA_Nether,
                        attrname = "passes")
colnames(FIFAm) <- c("GK1",
                     "DF3",
                     "DF4",
                     "DF5",
                     "MF6",
                     "FW7",
                     "FW9",
                     "MK10",
                     "FW11",
                     "DF2",
                     "MF8")
rownames(FIFAm) <- c("GK1",
                     "DF3",
                     "DF4",
                     "DF5",
                     "MF6",
                     "FW7",
                     "FW9",
                     "MK10",
                     "FW11",
                     "DF2",
                     "MF8")

palf <- colorRampPalette(c("#669999",
                           "#003333"))
heatmap(FIFAm,
        Rowv = NA,
        Colv = NA,
        col =  palf(60),
        scale = "none",
        margins = c(11,
                    11))


```

# Creating network diagrams with other **R** packages
## Network Diagrams with *ggplot2*

the function
```{r}
edgeMaker <- function(whichRow, len = 100, curved = TRUE){
  fromC <- layoutCoordinates[adjacencyList[whichRow, 1], ]
  toC <- layoutCoordinates[adjacencyList[whichRow, 2], ]
  graphCenter <- colMeans(layoutCoordinates)
  bezierMid <- c(fromC[1], toC[2])
  distance1 <- sum((graphCenter - bezierMid)^2)
  if(distance1 < sum((graphCenter - c(toC[1],
                                      fromC[2]))^2)){
    bezierMid <- c(toC[1], fromC[2])
  }
  bezierMid <- (fromC + toC + bezierMid) / 3
  if(curved == FALSE){
    bezierMid <- (fromC + toC) / 2
  }
  edge <- data.frame(bezier(c(fromC[1],
                              bezierMid[1],
                              toC[1]),
                            c(fromC[2],
                              bezierMid[2],
                              toC[2]),
                            evaluation = len))
  edge$Sequence <- 1:len
  edge$Group <- paste(adjacencyList[whichRow,
                                    1:2],
                      collapse = ">")
  return(edge)
}
```

using the function
```{r}
library(sna)
library(ggplot2)
library(Hmisc)

data("FIFA_Nether")
fifi.edge <- as.edgelist.sna(FIFA_Nether,
                             attrname = "passes")
fifi.edge <- data.frame(fifi.edge)
names(fifi.edge)[3] <- "value"
fifi.edge <- fifi.edge[fifi.edge$value >9, ]
adjacencyList <- fifi.edge

layoutCoordinates <- gplot(network(fifi.edge))
allEdges <- lapply(1:nrow(fifi.edge), 
                   edgeMaker, len = 500, curved = TRUE)
allEdges <- do.call(rbind, allEdges)
```

now the plot
```{r}
new_theme_empty <- theme_bw()
new_theme_empty$line <- element_blank()
new_theme_empty$rect <- element_blank()
new_theme_empty$strip.text <- element_blank()
new_theme_empty$axis.text <- element_blank()
new_theme_empty$plot.title <- element_blank()
new_theme_empty$axis.title <- element_blank()
new_theme_empty$plot.margin <- structure(c(0, 0, -1, -1),
                                         unit = "lines",
                                         valid.unit = 3L,
                                         class = "unit")

zp1 <- ggplot(allEdges) +
  geom_path(aes(x = x, y=y,
                group = Group,
                color = Sequence,
                size = -Sequence)) +
  geom_point(data = data.frame(layoutCoordinates),
             aes(x = x, y = y),
             size = 4,
             pch = 21,
             color = "black",
             fill = "gray") +
  scale_color_gradient(low = gray(0),
                       high = gray(9/10),
                       guide = "none") +
  scale_size(range = c(1/10, 1.5),
             guide = "none") +
  new_theme_empty
print(zp1)

```




