---
title: "Chapter 4"
author: "Nick Lauerman"
date: ""
output: 
  pdf_document: 
    fig_caption: yes
    fig_height: 6.5
    fig_width: 6.5
    toc: yes
    toc_depth: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_chunk$set(cache = TRUE)
#knitr::opts_chunk$set(cache.path = "./Cache/")
```

# Libraries and data used
## Libraries
```{r}
library(UserNetR)
library(statnet)
#library(igraph) will be loaded in flow to prevent interferance with statnet
library(intergraph)

```

## Data
```{r}
data("Moreno")
data("Bali")
```

# chanlage of net vis
```{r}
op <- par(mar = rep(0, 4),
          mfrow = c(1, 2))
plot(Moreno,
     mode = "circle",
     vertex.cex = 1.5)
plot(Moreno,
     mode = "fruchtermanreingold",
     vertex.cex = 1.5)
par(op)
```

# Aesthetics of Network Layouts
```{r}
op <- par(mar = c(0,0,4,0),
          mfrow = c(1,2))
gplot(Moreno,
      gmode = "graph",
      mode = "random",
      vertex.cex = 1.5,
      main = "Random layout")
gplot(Moreno,
      gmode = "graph",
      mode = "fruchtermanreingold",
      vertex.cex = 1.5,
      main = "Fruchterman - Reingold")
par(op)
```

# basic plotting algorithms and methods
```{r}
op <- par(mar = c(0,0,4,0),
          mfrow = c(2,3))
gplot(Bali,
      gmode = "graph",
      edge.col = "grey75",
      vertex.cex = 1.5,
      mode = "circle",
      main = "circle")

gplot(Bali,
      gmode = "graph",
      edge.col = "grey75",
      vertex.cex = 1.5,
      mode = "eigen",
      main = "eigen")

gplot(Bali,
      gmode = "graph",
      edge.col = "grey75",
      vertex.cex = 1.5,
      mode = "random",
      main = "random")

gplot(Bali,
      gmode = "graph",
      edge.col = "grey75",
      vertex.cex = 1.5,
      mode = "spring",
      main = "spring")

gplot(Bali,
      gmode = "graph",
      edge.col = "grey75",
      vertex.cex = 1.5,
      mode = "fruchtermanreingold",
      main = "fruchterman - reingold")

gplot(Bali,
      gmode = "graph",
      edge.col = "grey75",
      vertex.cex = 1.5,
      mode = "kamadakawai",
      main = "kamadakawai")

par(op)
```

## finer control over netwaork layout
```{r}
mycoords1 <- gplot(Bali,
                   gmode = "graph",
                   vertex.cex = 1.5)
mycoords2 <- mycoords1
mycoords2[,2] <- mycoords1[,2] * 1.5
mycoords1
mycoords2

op <- par(mar = c(4, 3, 4, 3),
          mfrow = c(1, 2))
gplot(Bali,
      coord = mycoords1,
      vertex.cex = 1.5,
      suppress.axes = FALSE,
      ylim = c(min(mycoords2[,2]) - 1,
               max(mycoords2[,2]) + 1),
      main = "Orginal coordinates")
gplot(Bali,
      coord = mycoords2,
      vertex.cex = 1.5,
      suppress.axes = FALSE,
      ylim = c(min(mycoords2[,2]) - 1,
               max(mycoords2[,2]) + 1),
      main = "Modified coordinates")
par(op)
```

## network graph layout *igraph*
```{r}
detach(package:statnet, unload = TRUE)
detach(package:sna, unload = TRUE)
detach(package:tsna, unload = TRUE)
detach(package:ergm.count, unload = TRUE)
detach(package:tergm, unload = TRUE)
detach(package:networkDynamic, unload = TRUE)
detach(package:ergm, unload = TRUE)
detach(package:network, unload = TRUE)
detach(package:statnet.common, unload = TRUE)
library(igraph)
```
```{r}
iBali <- asIgraph(Bali)
op <- par(mar = c(0,0,3,0),
          mfrow = c(1,3))

plot(iBali,
     layout = layout_in_circle,
     main = "Circle")

plot(iBali,
     layout = layout_randomly,
     main = "Random")

plot(iBali,
     layout = layout_with_kk,
     main = "Kamada - Kawai")

par(op)
```

