---
title: "Actor Prominence \n Chapter 7"
author: "Nick Lauerman"
date: "Started 26-Feb-2020"
output: 
  pdf_document: 
    fig_caption: yes
    fig_height: 6.5
    fig_width: 6.5
    toc: yes
    toc_depth: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_chunk$set(cache = TRUE)
#knitr::opts_chunk$set(cache.path = "./Cache/")
```

# Libraries and data used
## Libraries
```{r}
library(UserNetR)
library(statnet)
library(RColorBrewer)
```

## Data
```{r}
data(DHHS)
data("Bali")
```

# Centerality: Prominence for undirected nets
```{r}
net_mat <- rbind(c(0,1,1,0,0,0,0,0,0,0),
                 c(1,0,1,0,0,0,0,0,0,0),
                 c(1,1,0,1,1,0,1,0,0,0),
                 c(0,0,1,0,1,0,0,0,0,0),
                 c(0,0,1,1,0,1,0,0,0,0),
                 c(0,0,0,0,1,0,1,0,0,0),
                 c(0,0,1,0,0,1,0,1,0,0),
                 c(0,0,0,0,0,0,1,0,1,1),
                 c(0,0,0,0,0,0,0,1,0,0),
                 c(0,0,0,0,0,0,0,1,0,0))
rownames(net_mat) <- colnames(net_mat) <- letters[1:10]
net_mat
net <- network(net_mat) # from following section
gplot(net,
      gmode = "graph",
      mode = "fruchtermanreingold",
      vertex.cex = 1.5,
      displaylabels = TRUE)
```

## Three Common measure of Centerality
### Degree Centrality
```{r}
# net <- network(net_mat) # executed above
net %v% "vertex.names"
degree(net,
       gmode = "graph")
```

### Closeness Centrality
```{r}
closeness(net,
          gmode = "graph")
```

### Betweenness Centrality
```{r}
betweenness(net,
            gmode = "graph")
```

## Centrality measures in *R*
```{r}
df.prom <- data.frame(
  deg = degree(DHHS),
  cls = closeness(DHHS),
  btw = betweenness(DHHS),
  evc = evcent(DHHS),
  inf = infocent(DHHS),
  flb = flowbet(DHHS)
)
cor(df.prom)
```

## Centeralization: Network Level Indices of Centerality
```{r}
dum1 <- rbind(c(1,2),
              c(1,3),
              c(1,4),
              c(1,5))
star_net <- network(dum1,
                    directed = FALSE)
dum2 <- rbind(c(1,2),
              c(2,3),
              c(3,4),
              c(4,5),
              c(5,1))
circle_net <- network(dum2,
                      directed = FALSE)
par(mar = c(4, 4, 0.1, 0.1))
my_pal <- brewer.pal(5, "Set2")
gplot(star_net,
      usearrows = FALSE,
      displaylabels = FALSE,
      vertex.cex = 2,
      vertex.col = my_pal[1],
      edge.lwd = 0,
      edge.col = "grey50",
      xlab = "Star Graph")
gplot(circle_net,
      usearrows = FALSE,
      displaylabels = FALSE,
      vertex.cex = 2,
      vertex.col = my_pal[3],
      edge.lwd = 0,
      edge.col = "grey50",
      xlab = "Circle Graph")
closeness(circle_net)
centralization(circle_net,
               closeness)
closeness(star_net)
centralization(star_net,
                 closeness)

```

## Reporting Centrality
```{r}
str(degree(Bali))
summary(degree(Bali))
rolecat <- Bali %v% "role"
gplot(Bali,
      usearrows = FALSE,
      displaylabels = TRUE,
      vertex.col = my_pal[as.factor(rolecat)],
      edge.lwd = 0,
      edge.col = "grey50")
legend("topright",
       legend = c("BM",
                  "CT",
                  "OA",
                  "SB",
                  "TL"),
       col = my_pal,
       pch = 19,
       pt.cex = 2.0)

df.prom2 <- data.frame(
  degree = degree(Bali),
  closeness = closeness(Bali),
  betweenness = betweenness(Bali)
)
row.names(df.prom2) <- Bali %v% "vertex.names"
df.promsort <- df.prom2[order(-df.prom2$degree), ]
cd <- centralization(Bali, degree)
cc <- centralization(Bali, closeness)
cb <- centralization(Bali, betweenness)
df.promsort <- rbind(df.promsort, c(cd, cc, cb))
#row.names(df.promsort)[18] <- "\\empf[Centraluzation}" suspected for mark down for book
row.names(df.promsort)[18] <- "Centraluzation"
df.promsort

deg <- degree(Bali, rescale = TRUE)
op <- par(mfrow = c(1,2))
gplot(Bali,
      usearrows = F,
      displaylabels = T,
      vertex.cex = deg,
      vertex.col = my_pal[as.factor(rolecat)],
      edge.lwd = 0,
      edge.col = "grey25",
      main = "Too small")
gplot(Bali,
      usearrows = F,
      displaylabels = T,
      vertex.cex = deg * 20,
      vertex.col = my_pal[as.factor(rolecat)],
      edge.lwd = 0,
      edge.col = "grey25",
      main = "a little better")
par(op)

gplot(Bali,
      usearrows = F,
      displaylabels = T,
      vertex.cex = deg * 12,
      vertex.col = my_pal[as.factor(rolecat)],
      edge.lwd = 0.5,
      edge.col = "grey75")
legend("topright",
       legend = c("BM",
                  "CT",
                  "OA",
                  "SB",
                  "TL"),
       col = my_pal,
       pch = 19,
       pt.cex = 2.0)
```

# Cutpoints and Bridges
```{r}
cpnet <- cutpoints(net,
                   mode = "graph",
                   return.indicator = TRUE)
gplot(net,
      gmode = "graph",
      vertex.col = cpnet + 2,
      #coord = coords, not surewhat coords does not exest
      jitter = FALSE,
      displaylabels = TRUE)

net2 <- net
components(net2)
delete.vertices(net2, 7)
components(net2)
gplot(net2,
      gmode = "graph",
      vertex.col = 2,
      jitter = FALSE,
      displaylabels = TRUE)
```
```{r}
bridges <- function(dat,
                    mode = "graph",
                    connected = c("strong",
                                  "weak")){
  e_cnt <- network.edgecount(dat)
  if(mode == "graph"){
    cmp_cnt <- components(dat)
    b_vec <- rep(FALSE, e_cnt)
    for(i in 1:e_cnt){
      dat2 <- dat
      delete.edges(dat2, i)
      b_vec[i] <- (components(dat2) != cmp_cnt)
    }
  }
  else{
    cmp_cnt <- components(dat, connected = connected)
    b_vec <- rep(FALSE, e_cnt)
    for(i in 1:e_cnt){
      dat2 <- dat
      delete.edges(dat2, i)
      b_vec[i] <- (components(dat2, connected = connected) != cmp_cnt)
    }
  }
  return(b_vec)
}
```
```{r}
bridges(net)
brnet <- bridges(net)
gplot(net,
      gmode = "graph",
      vertex.col = "red",
      edge.col = brnet + 2,
      jitter = FALSE,
      displaylabels = TRUE)
```






