---
title: "Chapter 2"
author: "Nick Lauerman"
date: "13 February 2020"
output: 
  pdf_document: 
    fig_caption: yes
    fig_height: 6.5
    fig_width: 6.5
    toc: yes
    toc_depth: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
knitr::opts_chunk$set(cache.path = "./Cache/")
```

# Libraries and data used
## Libraries
```{r, cache=FALSE}
library(statnet)
library(UserNetR)
```
## Data
```{r}
data(Moreno)
```

# Simple Visualization
```{r}
gender <- Moreno %v% "gender"
```
```{r, cache=FALSE}
plot(Moreno,
     vertex.col = gender +2,
     vertex.cex = 1.2)
```

# Basic Description
## Size 
```{r}
network.size(Moreno)
summary(Moreno, print.adj = FALSE)
```

## Density
```{r}
den_hand <- 2*46/(33*32)
gden(Moreno)
```

## components
```{r}
components(Moreno)
```

## Diameter
```{r}
lgc <- component.largest(Moreno,
                         result = "graph")
gd <- geodist(lgc)
max(gd$gdist)
```

## Clustering coef
```{r}
gtrans(Moreno,
       mode = "graph")
```
