---
title: "Random Network Models - Chapter 10"
author: "Nick Lauerman"
date: "Started 12-Mar-2020"
output: 
  pdf_document: 
    fig_caption: yes
    fig_height: 6.5
    fig_width: 6.5
    toc: yes
    toc_depth: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries and Data
## Libraries used
```{r}
library(igraph)
library(lattice)
#library(ergmharris)
```

## data sets used
```{r}
#data("lhds")
```

# Models of Network Structures and Formation
## Erdos-Renyi Random Graph Model
```{r, cache=TRUE, cache.path="./Cache/"}
g <- erdos.renyi.game(n = 12,
                      10,
                      type = "gnm")
g
graph.density(g)
```
```{r}
op <- par(mar = c(0,1,3,1),
          mfrow = c(1,2))
plot(erdos.renyi.game(n = 12,
                      10,
                      type = "gnm"),
     vertex.color = 2,
     main = "first random graph")
plot(erdos.renyi.game(n = 12,
                      10,
                      type = "gnm"),
     vertex.color = 4,
     main = "second random graph")
par(op)
```
```{r ,cache=TRUE, cache.path="./Cache/"}
g <- erdos.renyi.game(n = 1000,
                      0.005,
                      type = "gnp")
```
```{r}
plot(degree.distribution(g),
     type = "b",
     xlab = "Degree",
     ylab = "Proportion")
```
```{r, cache=TRUE, cache.path="./Cache/"}
crnd <- runif(500, 1, 8)
cmp_prp <- sapply(crnd, function(x)
     max(clusters(erdos.renyi.game(n = 1000,
                                   p = x/999))$csize)/1000)
smoothingSpline <- smooth.spline(crnd,
                                 cmp_prp,
                                 spar = 0.25)
```
```{r}
plot(crnd, cmp_prp,
     col = "grey60",
     xlab = "Avg. Degree",
     ylab = "Largest Component Proportion")
lines(smoothingSpline,
      lwd = 1.5)
```
```{r, cache=TRUE, cache.path="./Cache/"}
n_vect <- rep(c(50, 100, 500, 1000, 5000), 
              each = 50)
g_diam <- sapply(n_vect, function(x)
     diameter(erdos.renyi.game(n = x,
                               p = 6/(x - 1))))
library(lattice)
```
```{r}
bwplot(g_diam ~ factor(n_vect),
       panel = panel.violin,
       xlab = "Network Size",
       ylab = "Diameter")
```

## Small-World Model
```{r, cache=TRUE, cache.path="./Cache/"}
g1 <- watts.strogatz.game(dim = 1,
                          size = 30,
                          nei = 2,
                          p = 0)
g2 <- watts.strogatz.game(dim = 1,
                          size = 30,
                          nei = 2,
                          p = 0.05)
g3 <- watts.strogatz.game(dim = 1,
                          size = 30,
                          nei = 2,
                          p = 0.20)
g4 <- watts.strogatz.game(dim = 1,
                          size = 30,
                          nei = 2,
                          p = 1)
```
```{r}
op <- par(mar = c(2,1,3,1),
          mfrow = c(2,2))
plot(g1,
     vertex.label = NA,
     main = expression(paste(italic(p), "= 0")),
     layout = layout_with_kk)
plot(g2,
     vertex.label = NA,
     main = expression(paste(italic(p), "= 0.05")))
plot(g3,
     vertex.label = NA,
     main = expression(paste(italic(p), "= 0.20")))
plot(g4,
     vertex.label = NA,
     main = expression(paste(italic(p), "= 1")))
par(op)

```
```{r, cache=TRUE, cache.path="./Cache/"}
g100 <- watts.strogatz.game(dim = 1,
                            size = 100,
                            nei = 2,
                            p = 0)
g100
diameter(g100)

p_vect <- rep(1:30,
              each = 10)
g_diam <- sapply(p_vect,
                 function(x)
                      diameter(watts.strogatz.game(dim = 1,
                                                   size = 100,
                                                   nei = 2,
                                                   p=x/200)))
smoothingSpline <- smooth.spline(p_vect, g_diam,
                                 spar = 0.35)
```
```{r}
plot(jitter(p_vect, 1),
     g_diam,
     col = "grey60",
     xlab = "Number of rewired edges",
     ylab = "Diameter")
lines(smoothingSpline,
      lwd = 1.5)
```


## Scale-Free Models
```{r}
# from chapter 5
rescale <- function(nchar, low, high){
  min_d <- min(nchar)
  max_d <- max(nchar)
  rscl <- ((high - low) * (nchar - min_d)) /
    (max_d - min_d) + low
  return(rscl)
}
```

```{r, cache=TRUE, cache.path="./Cache/"}
g <- barabasi.game(500,
                   directed = FALSE)
V(g)$color <- "lightblue"
V(g)[degree(g) > 9]$color <- "red"
node_size <- rescale(nchar = degree(g),
                     low = 2,
                     high = 8)
```
```{r}
plot(g,
     vertex.label = NA,
     vertex.size = node_size)
```
```{r, cache=TRUE, cache.path="./Cache/"}
median(degree(g))
mean(degree(g))
table(degree(g))
```
```{r}
op <- par(mfrow = c(1,2))
plot(degree.distribution(g),
     xlab = "Degree",
     ylab = "Proportion")
plot(degree.distribution(g),
     log = "xy",
     xlab = "Degree",
     ylab = "Proportion")
par(op)
```
```{r, cache=TRUE, cache.path="./Cache/"}
g <- barabasi.game(500,
                   out.dist = c(0.25, 0.5, 0.25),
                   directed = FALSE,
                   zero.appeal = 1)
V(g)$color <- "lightblue"
V(g)[degree(g) > 9]$color <- "red"
node_size <- rescale(nchar = degree(g),
                     low = 2,
                     high = 8)
```
```{r}
plot(g,
     vertex.label = NA,
     vertex.size = node_size)
```
```{r, cache=TRUE, cache.path="./Cache/"}
g1 <- barabasi.game(10, 
                    m = 1,
                    directed = FALSE)
g2 <- barabasi.game(25, 
                    m = 1,
                    directed = FALSE)
g3 <- barabasi.game(50, 
                    m = 1,
                    directed = FALSE)
g4 <- barabasi.game(100, 
                    m = 1,
                    directed = FALSE)
```
```{r}
op <- par(mfrow = c(2,2),
          mar = c(4, 0, 1, 0))
plot(g1,
     vertex.label = NA,
     vertex.size = 3,
     xlab = " n = 10")
plot(g2,
     vertex.label = NA,
     vertex.size = 3,
     xlab = " n = 25")
plot(g3,
     vertex.label = NA,
     vertex.size = 3,
     xlab = " n = 50")
plot(g4,
     vertex.label = NA,
     vertex.size = 3,
     xlab = " n = 100")
par(op)
```

# Compairing Random Models to Emperical models

Required data set not availble!

