---
title: "Effective Network Graphic Design"
sbutitle: "Chapter 5"
author: "Nick Lauerman"
date: ""
output: 
  pdf_document: 
    fig_caption: yes
    fig_height: 6.5
    fig_width: 6.5
    toc: yes
    toc_depth: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_chunk$set(cache = TRUE)
#knitr::opts_chunk$set(cache.path = "./Cache/")
```

# Libraries and data used
## Libraries
```{r}
library(UserNetR)
library(statnet)
library(RColorBrewer)
```

## Data
```{r}
data("Bali")
```

# basic principles
# design Elements
## node color
```{r}
gplot(Bali,
      vertex.col = "slateblue2",
      gmode = "graph")
col2rgb('slateblue2')
gplot(Bali,
      vertex.col = rgb(122, 103, 238,
                       maxColorValue = 255),
      gmode = "graph")
gplot(Bali,
      vertex.col = "#7A67EE",
      gmode = "graph")
ndum <- rgraph(300,
               tprob = 0.025,
               mode = "graph")
op <- par(mar = c(0, 0, 2, 0),
          mfrow = c(1, 2))
gplot(ndum,
      gmode = "graph",
      vertex.cex = 2,
      vertex.col = rgb(0, 0, 139,
                       maxColorValue = 255),
      edge.col = "grey80",
      edge.lwd = 0.5,
      main = "Fully Opaque")

gplot(ndum,
      gmode = "graph",
      vertex.cex = 2,
      vertex.col = rgb(0, 0, 139,
                       maxColorValue = 255,
                       alpha = 80),
      edge.col = "grey80",
      edge.lwd = 0.5,
      main = "Partly Transparent")
par(op)

rolelab <- get.vertex.attribute(Bali,
                                "role")
op <- par(mar = c(0, 0, 0, 0))
plot(Bali,
     usearrows = FALSE,
     vertex.cex = 1.5,
     label = rolelab,
     displaylabels = TRUE,
     vertex.col = "role")
par(op)

palette()

display.brewer.pal(5, "Dark2")

my_pal <- brewer.pal(5, "Dark2")
rolecat <- as.factor(get.vertex.attribute(Bali, "role"))
plot(Bali,
     vertex.cex = 1.5,
     label = rolelab,
     displaylabels = TRUE,
     vertex.col = my_pal[rolecat])
```

## Node Shape
```{r}
op <- par(mar = c(0, 0, 0, 0))
sidenum <- 3:7
plot(Bali,
     usearrows = FALSE,
     vertex.cex = 4,
     displaylabels = FALSE,
     vertex.sides = sidenum[rolecat])
par(op)
```

## Node Size
```{r}
op <- par(mar = c(0, 0, 1, 0),
          mfrow = c(1,3))
plot(Bali,
     vertex.cex = 0.5,
     main = "Too small")
plot(Bali,
     vertex.cex = 2,
     main = "Just right")
plot(Bali,
     vertex.cex = 6,
     main = "Too large")
par(op)

deg <- degree(Bali,
              gmode = "graph")
deg
cls <- closeness(Bali,
                 gmode = "graph")
cls
bet <- betweenness(Bali,
                   gmode = "graph")
bet

op <- par(mar = c(0, 0, 2, 1),
          mfrow = c(1,2))
plot(Bali,
     usearrows = T,
     vertex.cex = deg,
     main = "Raw")
plot(Bali,
     usearrows = F,
     vertex.cex = log(deg),
     main = "Adjusted")
par(op)

op <- par(mar = c(0, 0, 2, 1),
          mfrow = c(1,2))
plot(Bali,
     usearrows = T,
     vertex.cex = cls,
     main = "Raw")
plot(Bali,
     usearrows = F,
     vertex.cex = 4*cls,
     main = "Adjusted")
par(op)

op <- par(mar = c(0, 0, 2, 1),
          mfrow = c(1,2))
plot(Bali,
     usearrows = T,
     vertex.cex = bet,
     main = "Raw")
plot(Bali,
     usearrows = F,
     vertex.cex = sqrt(bet + 1),
     main = "Adjusted")
par(op)

rescale <- function(nchar, low, high){
  min_d <- min(nchar)
  max_d <- max(nchar)
  rscl <- ((high - low) * (nchar - min_d)) /
    (max_d - min_d) + low
  return(rscl)
}
plot(Bali,
     vertex.cex = rescale(deg, 1, 6),
     main = "Adjusted node size wth rescale function")
```

## node label
```{r }
get.vertex.attribute(Bali,
                     "vertex.names")
op <- par(mar = c(0, 0, 0, 0))
plot(Bali,
     displaylabels = TRUE,
     label.cex = 0.8,
     pad = 0.4,
     label.col = "darkblue")
par(op)

rolelab <- get.vertex.attribute(Bali, "role")
plot(Bali,
     usearrows = FALSE,
     label = rolelab,
     displaylabels = TRUE,
     label.col = "darkblue")
```

## Edge width
```{r}
op <- par(mar = c(0, 0, 0, 0))
IClevel <- Bali %e% "IC"
plot(Bali,
     vertex.cex = 1.5,
     edge.lwd  = 1.5 * IClevel)
par(op)
```

## edge color
```{r}
n_edge <- network.edgecount(Bali)
edge_cat <- sample(1:3,
                   n_edge,
                   replace = T)
linecol_pal <- c("blue",
                 "red",
                 "green")
plot(Bali,
     vertex.cex = 1.5,
     vertex.col = "grey25",
     edge.col = linecol_pal[edge_cat],
     edge.lwd = 2)
```

## edge type
```{r}
n_edge <- network.edgecount(Bali)
edge_cat <- sample(1:3,
                   n_edge,
                   replace = T)
line_pal <- c(2,
              3,
              4)
gplot(Bali,
      vertex.cex = 0.8,
      gmode = "graph",
      vertex.col = "grey50",
      edge.lwd = 1.5,
      edge.lty = line_pal[edge_cat])
```

## Legends
```{r}
my_pal <- brewer.pal(5, "Dark2")
rolecat <- as.factor(get.vertex.attribute(Bali,
                                          "role"))
plot(Bali,
     vertex.cex = rescale(deg, 1, 5),
     vertex.col = my_pal[rolecat])
legend("bottomleft",
       legend = c("BM",
                  "CT",
                  "OA",
                  "SB",
                  "TL"),
      col = my_pal,
      pch = 19,
      pt.cex = 1.5,
      bty = "n",
      title = "Terrorist Role"
      )
```







